Repository ChameleonFramework/Chameleon, pull requests merged in 2023-10, with the labels that each got.

#302 ci(release): fix releases not being published (fix #284)
  .github/workflows/release.yml
Labels: area: ci, type: bug: fix, size: S

#304 feat(examples): add metadata example
  example/src/main/java/dev/hypera/example/ChameleonExample.java
  example/src/main/java/dev/hypera/example/command/ExampleCommand.java
Labels: type: enhancement, size: S, area: example

#303 ci(gradle): submit dependency graph (resolves #301)
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: area: ci, size: S

#317 chore: improve bug_report issue template (fix #292)
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type: enhancement, size: S

#316 fix(platform): remove package-info.java (fix #314)
  platform-api/src/main/java/dev/hypera/chameleon/platform/package-info.java
Labels: type: bug: fix, area: platform, size: S
